17. LatihanBlogURLnamespace/Django_Project/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^post/(?P<slugInput>[\w-]+)/$', views.detailPost, name="detail"),
    url(r'^category/(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="category"),

]

17. LatihanBlogURLnamespace/Django_Project/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^blog/', include(('blog.urls','blog'),namespace = 'blog')),
    url(r'^admin/', admin.site.urls),
]

17. LatihanBlogURLnamespace/Django_Project/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    judul   = models.CharField(max_length=255)
    body    = models.TextField()
    category= models.CharField(max_length=255)
    publish = models.DateTimeField(auto_now_add = True)
    update  = models.DateTimeField(auto_now=True)
    slug    = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.judul)
        super(Post, self).save()

    def __str__(self):
        return "{}. {}".format(self.id,self.judul)

17. LatihanBlogURLnamespace/Django_Project/blog/views.py
# views blog
from django.shortcuts import render

from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul':'myBlog',
        'Content' : 'Jurnal MotivasiInspirasi',
        'Categories' :categories,
        'Posts': posts,
    }
    return render(request, 'blog/index.html',context)


def categoryPost(request, categoryInput):
    posts = Post.objects.filter(category=categoryInput)

    # mengambil nilai categories dan   distinct() untuk mengambil nilai unik
    categories = Post.objects.values('category').distinct()
    print(categories)
    
    context = {
        'Judul':'blog category',
        'Content' : 'Tampilkan Berdasarkan category',
        'Categories' :categories,
        'Posts': posts,
    }
    return render(request, 'blog/category.html',context)


def detailPost(request, slugInput):
    posts = Post.objects.get(slug=slugInput)
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul':'Blog deskripsi',
        'Content' : 'ini adalah deskripsi Blog',
        'Categories' :categories,
        'Posts': posts,
    }
    return render(request, 'blog/detail.html',context)

17. LatihanBlogURLnamespace/Django_Project/mywebsite/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    context = {
        'Judul':'motivasi inspirasi',
        'Content':'Ini adalah halaman home',
    }
    return render(request,'index.html', context)

17. LatihanBlogURLnamespace/Django_Project/blog/templates/blog/category.html
{% extends "base.html" %}

{% block Title %}
  {{Judul}}
{% endblock Title%}

{% block pageTitle %}
  {{Judul}}
{% endblock pageTitle %}

{% block contents %}
  {{Content}}

  <ul class="nav">

    <li class="nav-item">
      <a class="nav-link" href="/blog">
        ALL post
      </a>
    </li>

  {% for dataCategory in Categories %}
      <li class="nav-item">
        <a class="nav-link" href="/blog/category/{{dataCategory.category}}">
          {{dataCategory.category}}
        </a>
      </li>
  {% endfor %}
  </ul>

 

  {% for post in Posts %}
    <a href="/blog/post/{{post.slug}}" title="">
      <h1>{{post.judul}}</h1>
    </a>
   
    <p>{{post.publish}}</p>
    <!-- truncatchars untuk memotong huruf ditampilan disesuaikan kebutuhan -->
    
    <p>{{post.body|truncatechars:200}}</p>
  {% endfor%}
 
{% endblock contents %}

17. LatihanBlogURLnamespace/Django_Project/blog/templates/blog/detail.html
{% extends "base.html" %}

{% block Title %}
  {{Judul}}
{% endblock Title%}

{% block pageTitle %}
  {{Judul}}
{% endblock pageTitle %}

{% block contents %}
  {{Content}}

  
  <ul class="nav">

    <li class="nav-item">
      <a class="nav-link" href="/blog">
        ALL post
      </a>
    </li>

  {% for dataCategory in Categories %}
      <li class="nav-item">
        <a class="nav-link" href="/blog/category/{{dataCategory.category}}">
          {{dataCategory.category}}
        </a>
      </li>
  {% endfor %}
  </ul>

  <h1>{{Posts.judul}}</h1>
  <p>{{Posts.publish}}</p>
  <p>{{Posts.body}}</p>

{% endblock contents %}

17. LatihanBlogURLnamespace/Django_Project/blog/templates/blog/index.html
{% extends "base.html" %}

{% block Title %}
  {{Judul}}
{% endblock Title%}

{% block pageTitle %}
  {{Judul}}
{% endblock pageTitle %}

{% block contents %}
  {{Content}}

  <!-- halaman category -->
  <ul class="nav">

    <li class="nav-item">
      <!-- mengambil dari index url blog -->
      <a class="nav-link" href="{% url "blog:index" %}">
        ALL post
      </a>
    </li>

  {% for dataCategory in Categories %}
      <li class="nav-item">
        <!-- dirubah dengan slug -->
        <a class="nav-link" href="{% url "blog:category" categoryInput=dataCategory.category% }">
          {{dataCategory.category}}
        </a>
      </li>
  {% endfor %}
  </ul>

  <!-- slug halaman blog awal -->
  {% for post in Posts %}
    <a href="{% url "blog:detail" slugInput=post.slug %}" title="">
      <h1>{{post.judul}}</h1>
    </a>
   
    <p>{{post.publish}}</p>
    <p>{{post.body|truncatechars:200}}</p>
  {% endfor%}

{% endblock contents %}

17. LatihanBlogURLnamespace/Django_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block Title %}

      {% endblock Title %}
    </title>
    {% include "snippets/styles.html" %}
   
  </head>
  <body>
    {% include "snippets/navbar.html"%}
    <div class="container" style="margin-top:80px">
      <h1>
        {% block pageTitle %}
  
        {% endblock pageTitle %}
      </h1>
    </div>

    <div class="container bg-ligt shadow mt-5">
      {% block contents %}

      {% endblock contents%}


    </div>

  
    {% include "snippets/scripts.html"%}
   

  </body>
</html>

17. LatihanBlogURLnamespace/Django_Project/templates/index.html
{% extends "base.html" %} 

{% block header %}
  {{Judul}}
{% endblock header%} 

{% block pageTitle %}
  {{Judul}}
{% endblock pageTitle %}

{% block contents %}
  {{Content}}
{% endblock contents %} 