27. BlogClassBasedViewEnd/blog/artikel/urls.py
from django.conf.urls import url

from .views import (
    ArtikelListView,
    ArtikelDetailView,
    ArtikelKategoriListView,
    ArtikelCreateView,
    ArtikelManageView,
    ArtikelDeleteView,
    ArtikelUpdateView
    )

urlpatterns = [
    url(r'^manage/update/(?P<pk>\d+)$', ArtikelUpdateView.as_view(), name='update'),
    url(r'^manage/delete/(?P<pk>\d+)$', ArtikelDeleteView.as_view(), name='delete'),
    url(r'^manage/$', ArtikelManageView.as_view(), name='manage'),
    url(r'^tambah/$', ArtikelCreateView.as_view(), name='create'),
    url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$', ArtikelKategoriListView.as_view(), name='category'),
    url(r'^detail/(?P<slug>[\w-]+)$', ArtikelDetailView.as_view(), name='detail'),
    url(r'^(?P<page>\d+)$', ArtikelListView.as_view(), name='list'),
]

27. BlogClassBasedViewEnd/blog/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from .views import BlogHomeView
urlpatterns = [
    url(r'^artikel/', include(('artikel.urls', 'artikel'), namespace='artikel')),
    url(r'^$', BlogHomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
]

27. BlogClassBasedViewEnd/blog/artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
class Artikel(models.Model):
    judul   = models.CharField(max_length=255)
    isi     = models.TextField()
    kategori = models.CharField(max_length=255)
    published =models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug    = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug':self.slug}
        return reverse('artikel:detail', kwargs= url_slug)
        

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)

27. BlogClassBasedViewEnd/blog/artikel/forms.py
from django.forms import ModelForm

from .models import Artikel

class ArtikelForm(ModelForm):
    class Meta:
        model = Artikel
        fields = [
            'judul',
            'isi',
            'kategori',
        ]
        

27. BlogClassBasedViewEnd/blog/artikel/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy


from .models import Artikel
from .forms import ArtikelForm

# manageview
# 2. update
class ArtikelUpdateView(UpdateView):
    form_class = ArtikelForm
    model = Artikel
    template_name = "artikel/artikel_update.html"

# 1 delete
class ArtikelDeleteView(DeleteView):
    model = Artikel
    template_name = "artikel/artikel_delete_confirmation.html"
    success_url = reverse_lazy('artikel:manage')

class ArtikelManageView(ListView):
    model = Artikel
    template_name = "artikel/artikel_manage.html"
    context_object_name='artikel_list'

# membuat from
class ArtikelCreateView(CreateView):
    form_class = ArtikelForm
    template_name = "artikel/artikel_create.html"

# --------------------------------------------------------
# tampilan Home
class ArtikelPerKategori():
    model = Artikel

    def get_latest_artikel_each_kategori(self):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        queryset= []

        for kategori in kategori_list:
            # kategori = kategori yg 1 itu punya for dan kedua punya models
            # latest untuk pencarian terakhir
            artikel = self.model.objects.filter(kategori=kategori).latest('published')
            queryset.append(artikel)

        return queryset
        
# Create your views here.
# tampilan artikel
class ArtikelKategoriListView(ListView):
    model = Artikel
    template_name= "artikel/artikel_kategori_list.html"
    context_object_name = 'artikel_list'
    ordering = ['-published']
    paginate_by = 3

    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        # distict digunakan agagr tidak double
        # exclude mengambil sisa
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct().exclude(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_list': kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)



class ArtikelListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_list.html"
    # memberi nama
    context_object_name= 'artikel_list'
    # mengurutkan  dan mengunakan - urutan akan terbalik
    ordering = ['-published']
    # memberi pagination kelompok angka
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        # distict digunakan agagr tidak double
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list': kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = "artikel/artikel_detail.html"
    context_object_name = 'artikel'

    def get_context_data(self, *args, **kwargs):
        # distict digunakan agagr tidak double
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list': kategori_list})

        artikel_serupa = self.model.objects.filter(kategori= self.object.kategori).exclude(id=self.object.id)
        self.kwargs.update({'artikel_serupa':artikel_serupa})

        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

27. BlogClassBasedViewEnd/blog/mywebsite/views.py
from artikel.models import Artikel
from django.views.generic import TemplateView

from artikel.views import ArtikelPerKategori

class BlogHomeView(TemplateView, ArtikelPerKategori):
    template_name = "index.html"

    def get_context_data(self):
        queryset = self.get_latest_artikel_each_kategori
        context = {
            'latest_artikel_list': queryset,
        }

        return context

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_create.html
{% extends "base.html" %}


{% block page_title %}
    Create
{% endblock page_title %}


{% block contents %}
    <h1>Tambah Artikel</h1>
    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{form.judul.id_for_label}}">{{form.judul.label}} :</label>
            <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}">    
        </div>

        <div class="form-group">
            <label for="{{form.isi.id_for_label}}">{{form.isi.label}} :</label>
            <textarea name="{{form.isi.name}}" class="form-control" rows="10"  required id="{{form.isi.id_for_label}}"></textarea>
        </div>

        <div class="form-group">
            <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}} :</label>
            <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}">  
        </div>
        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
{% endblock contents %}
    
    

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_delete_confirmation.html
{% extends "base.html" %}


{% block page_title %}
    Delete Artikel
{% endblock page_title %}


{% block contents %}
    <h1>Delete Artikel Confirmation</h1>
    <p>Apakah benar anda ingin menghapus artike berikut</p>
    <h3>{{artikel.judul}}</h3>
    <p>{{artikel.published}}</p>
    <form method="POST">
        {% csrf_token %}

        <button class="btn btn-outline-success" type="submit">Ya</button>
        <button class="btn btn-outline-danger" type="submit" href=" {% url 'artikel:manage' %} ">Tidak</button>
    </form>
{% endblock contents %}
    

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_detail.html
{% extends "base.html" %}


{% block page_title %}
    {{artikel.judul}}
{% endblock page_title %}


{% block contents %}
<div class="row">
    <div class="col-md-8">
        <h1>{{artikel.judul}}</h1>
        <h5>Kategori: {{artikel.kategori}} | {{artikel.published}}</h5>
        <p>{{artikel.isi}}</p>
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">  
            <li class="list-group-item"><a href="{% url 'artikel:list' 1 %}"> <b>Semua Kategori</b> </a></li>
           {% for kategori in kategori_list  %}
                <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1 %}">{{kategori}}</a></li>
           {% endfor %} 
        </ul>

        <h3>Artikel Serupa</h3>
        <ul class="list-group list-group-flush">  
           {% for artikel in artikel_serupa  %}
           <!-- membatasi hanya 2 yang serupa -->
                {% if forloop.counter is not 3 %}
                    <li class="list-group-item">
                        <h5><a href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h5>
                        <p>{{artikel.published|date}}</p>
                    </li> 
                {% endif %}
           {% endfor %} 
           <li><a href=" {% url 'artikel:category' artikel.kategori 1 %} ">Selengkapnya</a></li>
        </ul>    
    </div>
</div>
    
{% endblock contents %}
    

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_kategori_list.html
{% extends "base.html" %}

{% block page_title %}

{% endblock page_title %}

{% block contents %}
<!-- pagination -->

<div class="row">
    <div class="col-md-8">
        <h2 class="border-bottom">Kategori: {{kategori}}</h2>
        {% if is_paginated %}
            <nav aria-label="artikelPage">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:category' kategori page_obj.previous_page_number %}">Previous</a>
                    </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true" >Previous</a>
                        </li>
                    {% endif %}
                    
                    {% for page in paginator.page_range %} 
                        {% if page is page_obj.number  %}
                            <li class="page-item active" aria-current="page">
                                <span href="#" class="page-link">{{page}} <span class="sr-only">(current)</span> </span>
                            </li> 
                        {% else %}
                            <li class="page-item">
                                <a href="{% url 'artikel:category' kategori page %}" class="page-link">{{page}}</a>
                            </li> 
                        {% endif %} 
                    {% endfor %}
                        

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:category' kategori page_obj.next_page_number %}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

            {% for artikel in artikel_list %}
                <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug  %}">{{artikel.judul}}</a></h3>
                <p>{{artikel.published}}</p>
                <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug  %}">Selengkapnya</a> </p>
            {% endfor %}
    </div>
    <div class="col-sm">
        <h3>Kategori lainya</h3>
        <ul class="list-group list-group-flush">  
            <li class="list-group-item"><a href="{% url 'artikel:list' 1 %}"> <b>Semua Kategori</b> </a></li>
           {% for kategori in kategori_list  %}
                <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1 %}">{{kategori}}</a></li>
           {% endfor %} 
        </ul>
        
    </div>
</div> 

{% endblock contents %}

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_list.html
{% extends "base.html" %}

{% block page_title %}

{% endblock page_title %}

{% block contents %}
<!-- pagination -->

<div class="row">
    <div class="col-md-8">
        {% if is_paginated %}
            <nav aria-label="artikelPage">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:list' page_obj.previous_page_number %}">Previous</a>
                    </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true" >Previous</a>
                        </li>
                    {% endif %}
                    
                    {% for page in paginator.page_range %} 
                        {% if page is page_obj.number  %}
                            <li class="page-item active" aria-current="page">
                                <span href="#" class="page-link">{{page}} <span class="sr-only">(current)</span> </span>
                            </li> 
                        {% else %}
                            <li class="page-item">
                                <a href="{% url 'artikel:list' page %}" class="page-link">{{page}}</a>
                            </li> 
                        {% endif %} 
                    {% endfor %}
                        
                    <!-- untuk menjabarkan objectnya -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:list' page_obj.next_page_number %}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <!-- menampilkan -->
            {% for artikel in artikel_list %}
                <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug  %}">{{artikel.judul}}</a></h3>
                <p>Kategori: {{artikel.kategori}} | {{artikel.published}}</p>
                <!-- trunccatewords untuk membatasi kata yang ditampilkan -->
                <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug  %}">Selengkapnya</a> </p>
            {% endfor %}
        {% endif %}
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">
           
            {% for kategori in kategori_list  %}
                 <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1 %}">{{kategori}}</a></li>
            {% endfor %} 
               
          </ul>
    </div>
</div>


    

{% endblock contents %}

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_manage.html
{% extends "base.html" %}

{% block page_title %}
    Manage Artikel
{% endblock page_title %}
    

{% block contents %}
    <h1>Manage Artikel</h1>
    <a class="btn btn-primary btn-block" type="button" href= " {% url 'artikel:create' %} ">Tambah Artikel</a>
    <table class="table mt-4">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            <th scope="col">Kategori</th>
            <th scope="col">Published</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>          
            {% for artikel in artikel_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{artikel.judul}}</td>
                <td>{{artikel.kategori}}</td>
                <td>{{artikel.published}}</td>
                <td>
                    <a href=" {% url 'artikel:update' artikel.id %} " class="btn btn-warning" type="button">Edit</a>
                    <a href="  {% url 'artikel:delete' artikel.id %} " class="btn btn-danger" type="button">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      
{% endblock contents %}
    

27. BlogClassBasedViewEnd/blog/artikel/templates/artikel/artikel_update.html
{% extends "base.html" %}


{% block page_title %}
    Update
{% endblock page_title %}


{% block contents %}
    <h1>UpdateArtikel</h1>
    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{form.judul.id_for_label}}">{{form.judul.label}} :</label>
            <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}" value="{{form.judul.value}}">    
        </div>

        <div class="form-group">
            <label for="{{form.isi.id_for_label}}">{{form.isi.label}} :</label>
            <textarea name="{{form.isi.name}}" class="form-control" rows="10"  required id="{{form.isi.id_for_label}}">{{form.isi.value}}</textarea>
        </div>

        <div class="form-group">
            <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}} :</label>
            <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}" value="{{form.kategori.value}}">  
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
        <a href=" {% url 'artikel:manage' %} " class="btn btn-danger">Tidak</a>
    </form>
{% endblock contents %}
    
    