19. layoutingFormBootsrap/Django_Project/contact/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^$',views.index,name='index' ),
]

19. layoutingFormBootsrap/Django_Project/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/', include(('contact.urls','contact'), namespace='contact')),
    url(r'^admin/', admin.site.urls),
]

19. layoutingFormBootsrap/Django_Project/contact/models.py
from django.db import models

# Create your models here.

19. layoutingFormBootsrap/Django_Project/contact/forms.py
from django import forms
from django.forms.fields import EmailField

# create your views here


class ContactForm(forms.Form):

    # mengambil attrs di bottstrap form
    nama_lengkap  = forms.CharField(
        label = 'Nama Lengkap',
        max_length= 20,
        widget= forms.TimeInput(
            # attrs ini adalah atribute yang berisi dictionary
            attrs={
                'class':'form-control',
                'placeholder':'masukan nama lengkap anda',
            }
        )
    )
    jenis_kelamin = forms.ChoiceField(
        widget = forms.RadioSelect(
            attrs={
                'class':'form-check-input',
            }
        ),
        choices = [
            ('P','pria'),
            ('W','wanita'),
        ]
    )
    tanggal_lahir = forms.DateField(
        widget = forms.SelectDateWidget(
                    attrs = {
                        'class':'form-control col-sm-2',
                    },
                     years=range(1945,2020,1),
                 )
    )
    Email   = forms.EmailField(
        widget = forms.TimeInput(
            attrs= {
                'class':'form-control',
                'placeholder':'isi dengan email anda',
            }
        )
    )
    alamat  = forms.CharField(
        widget=forms.Textarea(
            attrs = {
                'class':'form-control',
                'placeholder':'isi alamat lengkap',
            }
        )
        
        )
    agree   = forms.BooleanField(
        widget = forms.CheckboxInput(
            attrs = {
                'class':'form-check-input',
            }
        )

    )

19. layoutingFormBootsrap/Django_Project/contact/views.py
from django.shortcuts import render

# Create your views here.
from .forms import ContactForm

def index(request):
    contact_form = ContactForm()
    context = {
        'heading' : 'contact',
        'data_form' : contact_form,
    }

    return render(request, 'contact/index.html', context)

19. layoutingFormBootsrap/Django_Project/mywebsite/views.py
from django.shortcuts import render

def index(request):
    context = {
        'heading':'Home',
        'content': 'ini adalah content',
    }

    return render(request,'index.html', context)

19. layoutingFormBootsrap/Django_Project/contact/templates/contact/index.html
{% extends "base.html" %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
   <form method="POST">
       {% csrf_token %}
       <!-- class disini menggunakan punya bootstrap -->
       <div class="form-group">
           {{ data_form.nama_lengkap.label_tag }}
           {{ data_form.nama_lengkap }}
       </div>
       <div class="form-group">
           {{ data_form.jenis_kelamin.label_tag}}
           {% for component in data_form.jenis_kelamin %}
                <div class="form-check">
                        <!-- ini radio button -->
                        {{ component.tag }}
                        <!-- for ini mengambil id jenis kelamin -->
                        <label for="{{component.id_for_label}}" class="form-check-label">
                            <!-- mengambil di form.py -->
                            {{component.choice_label}}
                        </label>
                </div>
           {% endfor%}
       </div>

       <div class="form-group">
           {{data_form.tanggal_lahir.label_tag}}
           <div class="form-row">
                {{data_form.tanggal_lahir}}
           </div>
           
       </div>

       <div class="form-group">
        {{ data_form.email.label_tag }}
        {{ data_form.email }}
       </div>

       <div class="form-group">
        {{ data_form.alamat.label_tag }}
        {{ data_form.alamat }}
       </div>

       <div class="form-group">
           <div class="form-check">
               {{data_form.agree}}
               <label for="{{data_form.agree.id_for_label}}">
                   {{data_form.agree.label}}
               </label>
           </div>
       </div>

       <button type="submit">Kirim</button>
   </form>
{% endblock content %}

<!-- untuk memastikan coding benar code page-source  -->

19. layoutingFormBootsrap/Django_Project/templates/base.html
<html>
<head>
    <title>
        {% block heading %}

        {% endblock heading %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Latihan Form</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item activate">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item activate">
                    <a class="nav-link" href="{% url 'contact:index' %}">contact</a>
                </li>
            </ul>
        </div>
      </nav>
      <div class="container">
        {% block content %}

        {% endblock content %}
      </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
</body>
</html>

19. layoutingFormBootsrap/Django_Project/templates/index.html
{% extends "base.html" %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
    {{content}}
{% endblock content %}